### Dockerfile
#
#   See https://github.com/ali-shaikh/docker

FROM alishaikh/alpine-base:latest
LABEL maintainer="Ali Shaikh <ali.az.shaikh@gmail.com>"

RUN apk add -U apache2-utils
RUN rm -rf /var/cache/apk/*